### ISSUE TITLE
Peer to peer review week5 day4

### ISSUE THREAD

**Issue by maryam0007** [gergitokusse/HTML-CSS-JavaScript-capstone-project-#2]
Hey Gergito, great job on making such a wonderful and attractive design but here are a few suggestions from our morning session group that can help it to be even more better:

- The image in place of hamburger is a good option but we think that it would be better if you use spans to make hamburger icon.
- We suggest you to use flex in main program section to make the alignment better
- We suggest you to apply the background for the speakers images as suggested by the design to stick to the given design.

**Comment by gergitokusse** [comment]
# 🙏🙏🙏⚽⚽⚽✔✔✔
